solidusio/solidus_i18n

- Gemfile
- app/assets/javascripts/spree/frontend/cart_decorator.js.coffee
- app/overrides/spree/shared/_main_nav_bar/cart_link.html.erb.deface
- solidus_i18n.gemspec
**Branch v.1.1 / Master**
Same thing as #1 (who will be v.1.0)
Difference is a version bump and removal of cart_decorator.js and override (which was added before the fork between my branch so not in this fork) who added missing params for automated translations of cart_link
> Development v1.1

- config/locales/de.yml
Recent changes made to admin translations in solidus moved many of the keys. This was done to better use the ActiveModel translation conventions.
I wrote a [script](https://github.com/StemboltHQ/solidus_i18n_convert) that scans through the locale files in solidus_i18n looking for missing keys when compared to `en.yml` in core. Since these translations are just moved, the script attempts to make the same moves in this locale as were made for english.
Reviews would be appreciated to find any blatant mistranslations.
> Convert de translations from solidus 1.2 -> 1.3

- config/locales/uk.yml
- `inventory unit` has no exact term, most matching is `розміщення
позиції замовлення`
- `line item` - `позиція замовлення`
- `promotion` - `промоакція`
- `reason` - `підстава`
- `refund` - `повернення грошей`
- reimbursement - `відшкодування`
- `capture` - `провести` або `використати`
- `backorderable` - (продаж) `під замовлення`
- `finalize` - `зафіксувати`
- `rma`, `return autorization` - `дозвіл на повернення товару`
- `tracking` - `відстеження`
- `shipment` - `відправлення`
- `shipping` - `доставка`
- `stock movement` - `рух залишків`
- `stock transfer` - `переміщення залишків`
- `details` - `докладно про...`
- `summary` - `коротко про...`
- `store credit` - `кредит магазину`, other definitions are more cumbersome,
e.g. `кошти, які клієнт може використати для оплати нових покупок`
- …
> Update uk locale

- README.md
It adds the following sections:
- supported languages
- next steps to change default locale 
- add more locales to the language toggle in the frontend
done with @giangjac
> Improve README with more instructions

- app/helpers/solidus_i18n/locale_helper.rb
- lib/solidus_i18n.rb
Sometimes Rails Module lockup causes errors like in https://github.com/solidusio-contrib/solidus_i18n/issues/73
Closes #73
> Explicitly use full constant name in locale helper

- config/locales/ru.yml
> add missing russian translations & corrections in russian translations

- config/locales/it.yml
Recent changes made to admin translations in solidus moved many of the keys. This was done to better use the ActiveModel translation conventions.
I wrote a [script](https://github.com/StemboltHQ/solidus_i18n_convert) that scans through the locale files in solidus_i18n looking for missing keys when compared to `en.yml` in core. Since these translations are just moved, the script attempts to make the same moves in this locale as were made for english.
Reviews would be appreciated to find any blatant mistranslations.
> Convert it translations from solidus 1.2 -> 1.3

- .travis.yml
The old version of bundler has now started failing with
NoMethodError: undefined method `to_specs' for nil:NilClass
> Remove bundler downgrade on travis

- config/locales/es.yml
**Refactor of es.yml** 
- The actual es.yml is quite old and phased out
- This new one is [v2.3.0](https://github.com/solidusio/solidus/releases/tag/v2.3.0) compatible, bumped from [en.yml](https://github.com/solidusio/solidus/commit/43eef78fd9e62d8f54a34288f07198eceffca0a4#diff-3329c5ee0df3de06561549745b116615 ) adding new key/values and removing the deprecate ones.
> Rebuild spanish yml descriptors from solidusio core

- .travis.yml
Travis recently switched to trusty build environment but broke
MySQL builds by removing database create privileges.
See: https://github.com/travis-ci/travis-ci/issues/8331
> Build on precise because of Travis MySQL problems

- config/locales/ca.yml
- config/locales/es.yml
The translation key for Canceled state is with double l: https://github.com/solidusio/solidus/blob/master/core/app/models/spree/return_item.rb#L83
> Fix reception states translations (spanish and catalan)

- config/locales/fr.yml
The appropriate translation for match any in french would be better suited with "un ou plusieurs" which translates to "one or more".
I also moved the string "aucun" to match_none.
> Update fr.yml in taxon_rule

- app/helpers/solidus_i18n/locale_helper.rb
- config/locales/en-IN.yml
- config/locales/es-MX.yml
- lib/solidus_i18n/locale.rb
- spec/helpers/locale_helper_spec.rb
- spec/lib/solidus_i18n/locale_spec.rb
We used to scan the `config/locales` directory of this project to determine available locales. This missed `en`, so that was added manually in a helper.
This PR changes that to instead scan `I18n.available_locales` for locales which have anything under `t(:spree)` and removes the hardcoded `English (EN)` (which is now also correctly "English (US)").
It also fixes `en-IN` and `es-MX` misidentifying as duplicated `"English (UK)"` and `"Castellano (ES)"` respectively.
> Improve Locale.all and all_locales_options

- .hound.yml
- app/assets/javascripts/spree/backend/edit_inline_locales.js.coffee.erb
- app/assets/javascripts/spree/backend/helpers.js.coffee.erb
- app/assets/javascripts/spree/backend/inline_table_locales.js.coffee
- app/assets/javascripts/spree/backend/templates/available_locales.hbs.erb
- app/assets/javascripts/spree/backend/translations.js.coffee
- app/controllers/spree/api/available_locales_controller.rb
- app/controllers/spree/locale_controller_decorator.rb
- app/helpers/solidus_i18n/locale_helper.rb
- app/models/spree/store_decorator.rb
- app/overrides/spree/shared/_main_nav_bar/locale_selector.html.erb.deface
- app/views/spree/admin/locales/show.html.erb
- app/views/spree/api/available_locales/show.json.jbuilder
- app/views/spree/api/available_locales/show.v1.rabl
- config/routes.rb
- db/migrate/20170523151209_add_available_locales_on_store.rb
- lib/solidus_i18n/controller_locale_helper.rb
- spec/controllers/locales_controller_spec.rb
- spec/features/admin/translations_spec.rb
- spec/features/translations_spec.rb
Modified the admin general settings page to select different available locales to each stores
rel #82
> Localize each store

- lib/solidus_i18n/engine.rb
This is a setting the host app should be making.
This is what it does: It adds the `default_locale` as
a fallback locale to all `available_locales`. This means
that for a store with e.g. a German default locale and en English
locale, missing English translations would be replaced by
their German equivalents rather than show up as missing
translations.
This fallback locale feature is very nice, but not very well
documented, and should IMO not be triggered from any gem's
initializer.
> Do not configure the fallback locale

- .travis.yml
- Gemfile
Removing unused `chromedriver-helper` gem fix the build. Aside, is not necessary install chrome in travis too.
> fix travis build

- solidus_i18n.gemspec
`NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.`
> Fix deprecation warning for #has_rdoc

- config/locales/de.yml
- i18n-tasks.yml
**This PR normalises German locales file.**
I followed the README and decided to update these locales since there are some missing. During this process, the task `i18n-tasks add-missing` normalised my file.
I decided to split my work into different PRs and avoid mixing the addition of new translations with the normalisation of the file.
Since the rubocop configuration is set to a maximum length for the line of 140 characters, I configured `i18n-tasks` to behave the same during the normalization.
I then simply run `i18n-tasks normalize` on the German translations. 
I think this task should be part of the CI, in order to keep our translations in order (pun intended).
If you also think this is a good thing, I will open a PR to introduce `i18n-tasks check-normalized` in the CI and fix all the …
> Normalize de locales file

- .travis.yml
Why do we use a matrix? The tests that we run are two and check things on the yml files that are not dependent on the solidus version. Can we simply remove it and speed up the CI or am I missing something?
> Remove Travis matrix

- README.md
- config/locales/es-MX.yml
There's no need for empty country names in this locale file. Removing.
Also, these lines cause `country.name` to be `nil` when calling `Spree::BaseHelper#available_countries` if the app's locale is `es-MX`.
> Remove empty country names from es-MX.yml

- config/locales/it.yml
I started from https://github.com/solidusio/solidus_i18n/pull/138 ( thanks @afdev82 ! ) and I used the `bundle exec i18n-tasks add-missing --nil-value --locale it` task to update the translations for solidus 2.9
I also proofread most of translations.
The PR is still in WIP because I think I will find more translations to fix in the next days.
> Update italian translations for solidus 2.9

- config/locales/es.yml
Adds missing translations for the Spanish main locale (es):
- `es.spree.view_product`
- `es.spree.master_sku`
- `es.spree.admin.tabs.zones`
- `es.spree.filter`
- `es.spree.modify_stock_count`
> Add es translations

- solidus_i18n.gemspec
This extension does no longer work together with newer versions of other gems like solidus_print_invoice or solidus_static_content, which rely on solidus_support (~> 0.5)
```
Bundler could not find compatible versions for gem "solidus_support":
In Gemfile:
solidus_i18n was resolved to 2.0.0, which depends on
solidus_support (~> 0.4.0)
solidus_print_invoice was resolved to 1.0.2, which depends on
solidus_support (~> 0.5)
```
> make gem work with solidus_support >0.5

- config/locales/de.yml
Contains necessary translations when using the backend in german. Otherwise the following errors occur on a fresh install:
```
app/views/spree/admin/orders/index.html.erb:153
translation missing: de.date.formats.default
```
```
app/views/spree/admin/shared/_js_locale_data.html.erb:9
undefined method `reject' for "translation missing: de.date.month_names":String
```
```
backend/vendor/assets/javascripts/solidus_admin/flatpickr/flatpickr.js:2167
TypeError: weekdays.join is not a function
(needs de.date.abbr_day_names)
```
```
/app/views/spree/admin/shared/_order_summary.html.erb:52
translation missing: de.time.formats.solidus.long
```
> add missing german translations necessary for backend

- config/locales/de.yml
short solidus time format necessary for 
```
backend/app/views/spree/admin/store_credits/show.html.erb:94
translation missing: de.time.formats.solidus.short
```
> add store credit translations and short solidus time format

- solidus_i18n.gemspec
I expect this to fail since solidus_dev_support depends on this gem and this gem depends on the failing solidus_dev_support.
> Allow Solidus 3

- config/locales/fr.yml
Added some missing french translations on the admin dashboard
- spree.name_contains: Nom contenant
- spree.shipment_number: Numéro de livraison
- spree.admin.tab.payments: Paiements
- spree.shipment_number: Numéro de livraison
> Added some missing french translations on the admin dashboard

- config/locales/en-GB.yml
- config/locales/en-IN.yml
- config/locales/en-NZ.yml
The `are_you_sure` alert confirmation message should end in a question mark in all English locales. If you look at other alert confirmation strings, you can see that they already end in question marks.
> Add missing punctuation for `are_you_sure` strings

- config/locales/fr.yml
`spree.admin_login` is only provided in four languages. I was a bit confused when the string started displaying in Spanish.
I'm happy to add other languages to this PR if that'd be preferred. But I don't speak any other languages.
> Add missing FR `spree.admin_login` translation

- config/locales/bg.yml
- config/locales/ca.yml
- config/locales/da.yml
- config/locales/de-CH.yml
- config/locales/en-AU.yml
- config/locales/en-GB.yml
- config/locales/en-IN.yml
- config/locales/en-NZ.yml
- config/locales/es-EC.yml
- config/locales/et.yml
- config/locales/fi.yml
- config/locales/id.yml
- config/locales/ko.yml
- config/locales/lv.yml
- config/locales/nb.yml
- config/locales/nl.yml
- config/locales/pt.yml
- config/locales/ro.yml
- config/locales/sl-SI.yml
- config/locales/th.yml
- config/locales/tr.yml
- config/locales/vi.yml
- config/locales/zh-CN.yml
- config/locales/zh-TW.yml
The way this is used, these empty translations will break portions of the admin, because the root `country_names` key is accessed and used as a hash. This breaks the admin in certain places if you use one of these locales, because it will use nil as the name for the countries and then try to call string methods on it.
> Remove empty country_names translations

- .circleci/config.yml
Run different Solidus versions on different jobs for better error handling.
We're now explicitly providing the ruby version to the executor while using a matrix configuration for better extensibility.
Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.
The following are mandatory for all PRs:
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Update CI configuration
