solidusio/solidus_i18n

- config/locales/de.yml
-- Made a change over the _line 548_ on `config/locales/de.yml` to fix a bug about the number precision format .
> Changed the number precision in `de.yml`

- config/locales/ja.yml
> Add Japanese language for ja.yml

- solidus_i18n.gemspec
https://github.com/solidusio-contrib/solidus_i18n/issues/85#issuecomment-289145475
> updates rails-i18n version dependency

- config/locales/es.yml
- Add missing punctuation
- Fix words typos
> Add missing punctuation symbols and fix typos

- config/locales/es-MX.yml
> Fix issue with wrong date format

- config/locales/fr.yml
Fix FR translation for "Order number"
> fix fr translation

- config/locales/pt-BR.yml
I did my best to add a LOT of missing translations and will use that on my current solidus project. Not sure if there's anything else that I'd have to do to contribute back to this, but here it is.
Would love another brazilian to take a look, but I imagine there are few of those around...
> Add missing pt-BR translations

- config/locales/de.yml
Update the German translations
> Update the German translations

- .travis.yml
- Gemfile
- solidus_i18n.gemspec
This PR aims to introduce the following changes:
* Update Travis build matrix (see commit's description for details)
* Gemfile & gemspec maintenance (see commit's description for details)
> Extension maintenance

- config/locales/pt-BR.yml
I added new translations to pt-BR Locale.
> added more translations to pt-BR locale

- config/locales/ru.yml
Hi guys,
New batch of translations!
> update of most russian translations

- config/locales/pt-BR.yml
Added some missing translations to brazilian portuguese and fixed some grammar mistakes.
> Improve pt-BR translations

- config/locales/de.yml
Product Screens, Promotions, User, Hints
> Added Translations for Backend

- config/locales/ru.yml
Hello guys!
New fixes and additions for russian language
> Fix existent russian translations and add new one

- solidus_i18n.gemspec
Drop support for ruby 2.4 and allow ruby 3
> Bump ruby version

- config/locales/en-IN.yml
Changed zipcode to pincode. 
Zipcode is known as Pin code through out India. Zipcode is not understood by many.
> Change zipcode to pincode

- config/locales/de.yml
Read the commit messages for the why
> Update German Refund and Returns translations

- CHANGELOG.md
- Rakefile
- solidus_i18n.gemspec
Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.
The following are mandatory for all PRs:
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Update extension to the new release process

- .circleci/config.yml
- Gemfile
Ref. solidusio/solidus#5042
Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.
The following are mandatory for all PRs:
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Adapt to new Solidus default branch name

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- Rakefile
Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.
The following are mandatory for all PRs:
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Update to the new "main" default branch
